on:
    pull_request:
        branches: [main, master]

    push:
        branches: [main, master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
